config/routes.rb
# Routes
Rails.application.routes.draw do
  resources :categories

  get 'orders/create'
  get 'admins/administration'

  resources :admins do
  end

  resources :products do
    resources :orders, only: :create
  end

  resources :orders, only: [:index,:destroy]

  resources :orders do
    member do
        patch :clearcart
        put :clearcart
      end
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :categories, except: [:show]

  resources :product_categories do
  end

  root to: 'products#index'
  devise_for :users

  concern :paginatable do
    get '(products/:page)', action: :index, on: :collection
  end
  resources :products, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/administration.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    <table class="table">
      <% @products.each do |product| %>
      <tr>
            <td> <%= product.name %> </td>
            <td> <%= product.description %> </td>
            <td>$<%= product.price %> </td>
            <td>  <%= link_to edit_product_path(product) do %>
                 <i class="fas fa-edit"></i><% end %></td>
            <td>  <%= link_to admin_path(product), method: :delete, remote:true, data: {confirm: "Estás seguro de eliminar el producto?"} do %>
                 <i class="fas fa-trash"></i><% end %></td>
      </tr>
      <% end %>
    </table>
  </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4">
        <%= link_to products_path, class: 'btn btn-warning col-md-8' do %>
          <i class="fas fa-undo-alt"></i> Volver<% end %>
      </div>
      <div class="col-md-4">
      </div>
    </div>
  </div>
  <br><br>
</div>

app/views/admins/index.html.erb
<div class="container bodysize">
  <h1 class="welcomeadmin">Bienvenido Administrador</h1>
  <div class="row">
    <div class="col-md-4">
      <%= link_to 'Agregar Categoria', new_category_path, class: "btn btn-primary col-12" %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Agregar Producto', new_product_path, class: "btn btn-primary col-12" %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Administrar Productos Existentes', admins_administration_path, class: "btn btn-primary col-12" %>
    </div>
  </div>
</div>