config/routes.rb
# Routes
Rails.application.routes.draw do
  resources :categories

  get 'orders/create'
  get 'admins/administration'

  resources :admins do
  end

  resources :products do
    resources :orders, only: :create
  end

  resources :orders, only: [:index,:destroy]

  resources :orders do
    member do
        patch :clearcart
        put :clearcart
      end
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :categories, except: [:show]

  resources :product_categories do
  end

  root to: 'products#index'
  devise_for :users

  concern :paginatable do
    get '(products/:page)', action: :index, on: :collection
  end
  resources :products, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  authorize_resource

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new(product: @product, user: current_user)
    @order.save
      respond_to do |format|
        format.js
        format.html { redirect_to orders_path, notice: 'El Producto fue agregado a tu carro!.' }
        format.json { head :no_content }
      end
  end

  def index
    @orders = current_user.orders
    @cont = []
    @orders.each do |count|
    @cont << count if count.payed == false
    end
  end

  def destroy
    @orders = Order.find(params[:id])
    @orders.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to orders_path, notice: 'El Producto fue agregado a tu carro!.' }
      format.json { head :no_content }
    end
  end

  def clearcart
    @orders = current_user.orders
    @orders.clear
    respond_to do |format|
      format.js
      format.html { redirect_to orders_path, notice: 'Carro Limpio!.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.js.erb
swal("Bien!", "Se agregó a tu orden!", "success");

app/views/orders/index.html.erb
<div class="container">
  <div class="row wrapper">
    <div class="col-md-8 main">
      <div id="cartelement" class="row">
        <div id ="backgrey" class=" col-md-12">
          <h3><strong>Carro de Compras:</strong> ( <%= @cont.count %> productos )</h3>
        </div>
      </div>
      <br>
      <% if @cont.empty? == false  %>
        <% @cont.each do |order| %>
        <% if order.payed == false  %>
        <div id="cartelement" id="backgrey" class="row content rounded">
            <div class="col-md-3 d-flex justify-content-center">
              <%= image_tag order.product.image.variant(resize: "100x100!") %>
            </div>
            <div class="col-md-5 d-flex justify-content-center">
              <%= order.product.name %> <br>
              <%= order.product.description %>
            </div>
            <div class="col-md-2 d-flex justify-content-center">
               $<%= order.product.price %>
            </div>
            <div class="col-md-2 d-flex justify-content-center">
              <%= link_to order, method: :delete, data: {confirm: "Estás seguro?"} do %>
                   <i class="fas fa-trash">  </i>  <% end %>
            </div>
          </div>
        <br>
        <% end  %>
        <% end %>
      <% else %>
        <div id="cartelement" id="backgrey" class="col-md-12">
          <h4>Carro vacio! </h4>
          <%= link_to "Sigue Comprando...", products_path, class: "btn btn-warning col-md-12" %>
        </div>
      <% end %>
    </div>
      <% if @cont.empty? == false %>
      <div class="col-md-4 sidebar rounded">
        <div>
          <h4>Resumen de tu Orden:</h4>
          <strong>TOTAL: $ </strong><%= @cont.map{|order| order.product.price }.sum %>
        </div>
        <br>
        <%= link_to clearcart_order_path(@cont), method: :put, data: {confirm: "Estás seguro de borrar todos los elementos de tu carro?"}, class: "btn btn-danger col-md-12" do %>
          <i class="far fa-times-circle"> Limpiar Carro</i><% end %>
        <%= link_to products_path, class: "btn btn-warning col-md-12" do %>
          <i class="fas fa-undo-alt"> Volver</i><% end %>
        <%= link_to pre_pay_billings_path, class: "btn btn-success col-md-12"  do %>
          <i class="fas fa-cart-plus"> Completa tu compra</i><% end %>
        </div>
      <% end %>
  </div>
</div>