config/routes.rb
# Routes
Rails.application.routes.draw do
  resources :categories

  get 'orders/create'
  get 'admins/administration'

  resources :admins do
  end

  resources :products do
    resources :orders, only: :create
  end

  resources :orders, only: [:index,:destroy]

  resources :orders do
    member do
        patch :clearcart
        put :clearcart
      end
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :categories, except: [:show]

  resources :product_categories do
  end

  root to: 'products#index'
  devise_for :users

  concern :paginatable do
    get '(products/:page)', action: :index, on: :collection
  end
  resources :products, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_finder.html.erb
<nav id="nav2" class="navbar navbar-expand-md navbar-dark bg-dark justify-content-center">
  <%= form_tag({controller: '/products', action: "index"}, method: :get, class: "formbtn") do %>
  <%= text_field_tag 'searchbox', params[:searchbox], placeholder: 'Busca por producto...' %>
  <%= submit_tag "Buscar", name: nil, class:"btn btn-outline-success btnsearch" %>
  <% end %>
</nav>

app/views/layouts/_footer.html.erb
<div class="container">
  <h6 id="follow-us">Siguenos en:</h6>
    <div class="row">
      <div>
        <ul class="social-network social-circle">
          <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#" class="icoInstagram" title="Instagram"><i class="fa fa-instagram"></i></a></li>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class=" navbar-nav">
    <% if user_signed_in? %>
      <% if current_user.avatar.attached? %>
    <li class = "showuser btn"><%= current_user.name %> <%= image_tag current_user.avatar.variant(resize: "50x50!"), class: "rounded-circle" %></li>
      <% else %>
    <li class = "showuser btn"><%= image_tag gravatar_image_url(current_user.email, size: 50), class: "rounded-circle" %></li>
      <% end %>
    <% end %>
  </ul>
  <div class="navbar-collapse collapse order-3 dual-collapse2" id="navbarSupportedContent">
    <ul class=" navbar-nav ml-auto">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
        <li class="btn">  <%= link_to admins_path, class: "btn btn-success col-12" do %>
              <i class="fas fa-home"></i> Home <% end %>
        <% else %>
        <li class="btn">  <%= link_to root_path, class: "btn btn-success col-12" do %>
              <i class="fas fa-home"></i> Home <% end %></li>
          <li class="btn">  <%= link_to orders_path, class: "btn btn-warning col-12" do %>
                <i class="fas fa-shopping-cart"></i> Mi Carro <% end %></li>
          <li class="btn">  <%= link_to billings_path, class: "btn btn-warning col-12" do %>
                <i class="fas fa-shopping-cart"></i> Mis Compras <% end %></li>
          <% end %>
      <% else %>
      <li class="btn">  <%= link_to root_path, class: "btn btn-success col-12" do %>
            <i class="fas fa-home"></i> Home <% end %></li>
      <% end %>
      <% if user_signed_in? %>
      <li class="btn">  <%= link_to edit_user_registration_path, class: "btn btn-warning col-12" do %>
            <i class="fas fa-user"></i> Mi Cuenta <% end %></li>
        <li class="btn">  <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-danger col-12" do %>
              <i class="fas fa-times"></i> Cerrar Sesión <% end %></li>
      <%else%>
      <li class="btn">  <%= link_to new_user_session_path, class: "btn btn-warning col-12" do %>
            <i class="fas fa-user"></i> Iniciar Sesión<% end %></li>
      <li class="btn">  <%= link_to new_user_registration_path, class: "btn btn-warning col-12" do %>
            <i class="fas fa-user-plus"></i> Registrarse <% end %></li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mitiendaonline</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/ba5c438f01.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
    <%= render 'layouts/navbar' %>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= render 'layouts/finder' %>
    <%= yield %>
  </body>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</html>